### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by wagnerluis1982** [andrewrapp/xbee-serial-server#2]
Leave a socket opened to everybody in the network is not very interesting.
What about have a way to authenticate the users before connect?

I'm not suggesting anything complex, but something like the HTTP BASIC authentication. And the users could come from a `users.xml` file passed by a command line argument.

**Comment by wagnerluis1982** [comment]
@andrewrapp, if you are not opposed to add another dependency, the [Apache Commons Configuration](https://commons.apache.org/proper/commons-configuration/) have a easy way to read almost any kind of config file.

**Comment by andrewrapp** [comment]
It's not a goal of this project to provide auth. I use it on a home network and there is no concern of an open port. Feel free to fork it or alternatively I would think you could achieve your auth goal through an external mechanism, perhaps using iptables and a ssh tunnel

**Comment by wagnerluis1982** [comment]
Understood. I think your idea of using a SSH tunnel will solve my problem, also solving as bonus the issue #1

**Comment by wagnerluis1982** [comment]
I just realized this is needless open.
